export interface PhysicsPreset {
  id: string;
  name: string;
  category: "Mechanics" | "Space & Rel" | "Waves & Sound" | "Quantum & Fields" | "Thermal/Fluid";
  template: "projectile" | "orbit" | "wave";
  gravity: number;
  mass: number;
  velocity: number;
  temperature: number;
  medium: string;
  formulas: string[];
  explain: string;
  steps: string;
  theory: string;
  hint: string;
  conceptAnalysis: string;
  commonPitfall: string;
  formulaConcept: string;
}

export const PHYSICS_PRESETS: PhysicsPreset[] = [
  // SECTION 1: MECHANICS (12 presets)
  {
    id: "proj_earth",
    name: "Classic Projectile Arc (Earth)",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 20,
    velocity: 45,
    temperature: 298,
    medium: "Standard Air",
    formulas: ["y(t) = v0*sin(θ)*t - 0.5*g*t²", "x(t) = v0*cos(θ)*t"],
    explain: "Parabolic trajectory modeling of a generic object under classical terrestrial gravity with standard atmospheric drag.",
    steps: "1. Launch with angle parameters.\n2. Ascend to global summit vertex (Apex).\n3. Accelerate downward uniformly.",
    theory: "Newtonian kinematics dictates parabolic paths when vertical force is continuous (gravitational) and horizontal force is zero.",
    hint: "Increase mass slider to monitor how inert friction vectors vary velocity profiles.",
    conceptAnalysis: "Gravity pulls with uniform g deceleration on the rising leg, and the vertical kinetic energy converts into local potential height.",
    commonPitfall: "Assuming horizontal speed diminishes in vacuum frameworks without friction bounds.",
    formulaConcept: "R = (v₀² * sin(2θ)) / g"
  },
  {
    id: "proj_moon",
    name: "Lunar Projectile Trajectory",
    category: "Mechanics",
    template: "projectile",
    gravity: 1.62,
    mass: 10,
    velocity: 35,
    temperature: 120,
    medium: "Lunar Vacuum",
    formulas: ["y(t) = v0*sin(θ)*t - 0.5 * 1.62 * t²", "x(t) = v0*cos(θ)*t"],
    explain: "Launches a low-mass coordinate under lunar structural conditions. Peak flight times scale significantly under 1.62 m/s².",
    steps: "1. Observe initial low gravity release.\n2. Notice highly elevated parabolic peaks.\n3. Verify perfectly symmetrical parabolic impact point.",
    theory: "Absence of gaseous atmospheres guarantees zero drag. Symmetrical quadratic curves remain mathematically pristine during vacuum motion.",
    hint: "Click the resume slider and monitor how low gravitational resistance translates into longer parabolic paths.",
    conceptAnalysis: "Weak local celestial gravity decreases acceleration forces, requiring much smaller work inputs to traverse long vertical spans.",
    commonPitfall: "Overestimating gravity drag coefficients inside lunar vacuum matrices.",
    formulaConcept: "t_flight = (2 * v₀ * sin(θ)) / 1.62"
  },
  {
    id: "car_crash",
    name: "Car Crash Momentum Impact",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 140,
    velocity: 55,
    temperature: 300,
    medium: "Dry Pavement",
    formulas: ["p_initial = m * v_launch", "Δp = F * Δt (Impulse)"],
    explain: "Models deceleration forces during an elastic vehicle collision with continuous pavement friction.",
    steps: "1. Accelerate object mass towards obstacle.\n2. Trigger collision impact.\n3. Measure rapid kinetic dissipation curves.",
    theory: "Momentum preservation governs vector speeds before impact. Deformational compression transfers friction energy into thermal waves.",
    hint: "Slam initial velocity to higher ranges to monitor proportional kinetic energy collapse on impact.",
    conceptAnalysis: "Kinetic energy scales with the square of system velocity. A 2x speed hike increases collision stress by exactly 4x.",
    commonPitfall: "Confusing total net kinetic energy with total conserved momentum vectors.",
    formulaConcept: "KE = 0.5 * m * v²"
  },
  {
    id: "friction_test",
    name: "Sliding Surface Friction Assessment",
    category: "Mechanics",
    template: "projectile",
    gravity: 12.5,
    mass: 65,
    velocity: 32,
    temperature: 295,
    medium: "Viscous Sandpaper",
    formulas: ["F_friction = μ_kinetic * N", "N = m * g"],
    explain: "Analyzes velocity degradation of structured mass sliding on rough, frictional granular surfaces.",
    steps: "1. Slide block across granular surface.\n2. Trace linear deceleration profile.\n3. Stop entirely as frictional energy matches mechanical kinetic limits.",
    theory: "Normal forces compile contact profiles, prompting microscopic electrostatic bonds to resist sliding vectors.",
    hint: "Vary mass scales to see normal load shifts influencing deceleration rates.",
    conceptAnalysis: "Frictional resistance works in complete opposition to velocity direction, translating physical kinetics into local thermal noise.",
    commonPitfall: "Believing surface area dimensions directly modify coefficient boundaries (μ) in standard Coulomb friction.",
    formulaConcept: "a_decel = -μ * g"
  },
  {
    id: "p_drop_mars",
    name: "Mars Landing Parachute Drag",
    category: "Mechanics",
    template: "projectile",
    gravity: 3.71,
    mass: 120,
    velocity: 28,
    temperature: 210,
    medium: "Rarefied CO₂ atmospheric layer",
    formulas: ["F_drag = 0.5 * Cd * ρ * A * v²", "F_net = m * 3.71 - F_drag"],
    explain: "Simulates descent vectors in thin Jovian or Martian atmospheres with deployment drag scaling.",
    steps: "1. Drop capsule from elevated coordinate.\n2. Deploy atmospheric parachute drags.\n3. Reach constant terminal velocity limits.",
    theory: "Terminal coordinates occur where the upwards force of drag scales to perfectly balance celestial downward pull.",
    hint: "Lower mass settings to reach terminal velocity faster in simulated test chambers.",
    conceptAnalysis: "Thin atmospheric medium reduces available density, creating low upward drag and yielding high terminal speeds.",
    commonPitfall: "Expecting earth-like sea-level parachute terminal curves in ultra-thin atmosphere bounds.",
    formulaConcept: "v_terminal = sqrt((2*m*g) / (Cd*ρ*A))"
  },
  {
    id: "galileo_slide",
    name: "Galilean Inclined Block sliding",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 50,
    velocity: 40,
    temperature: 293,
    medium: "Polished Wood track",
    formulas: ["a = g * sin(θ)", "v² = u² + 2*a*d"],
    explain: "Classic physics test measuring continuous acceleration down incline planes without rolling friction.",
    steps: "1. Position block on slanted ramp.\n2. Release mass slide uniformly.\n3. Measure consistent speed progression metrics.",
    theory: "Inclining ramp angles restricts gravity vector bounds down to proportional scale constraints.",
    hint: "Change ramp elevation dynamically to observe trigonometric acceleration trends.",
    conceptAnalysis: "Ramp incline scales the downward force, allowing scholars to inspect free-fall-like dynamics at comfortable slower speeds.",
    commonPitfall: "Neglecting frictional adjustments or assuming mass impacts the acceleration vector.",
    formulaConcept: "a = 9.8 * sin(θ)"
  },
  {
    id: "centripetal_tension",
    name: "Centripetal Tension Experiment",
    category: "Mechanics",
    template: "orbit",
    gravity: 9.8,
    mass: 40,
    velocity: 75,
    temperature: 298,
    medium: "Synthetic Wire",
    formulas: ["Fc = m * v² / r", "Tension = Fc"],
    explain: "Analyzes mechanical wire strain during continuous circular rotations at targeted angular configurations.",
    steps: "1. Spin point mass in orbital constraints.\n2. Observe inner tension vectors pulling inward.\n3. Measure tensile limits.",
    theory: "Inertia prompts the mass to pursue linear paths, while central wire constraints redirect velocity continuously toward center.",
    hint: "Multiply rotation speed to see centripetal stress scale exponentially.",
    conceptAnalysis: "Tension works solely to alter velocity direction, doing zero physical work on the rotating system.",
    commonPitfall: "Confusing centripetal force (inward constraint) with centrifugal forces (imaginary inertial frame effects).",
    formulaConcept: "T = m * ω² * r"
  },
  {
    id: "impulse_hammer",
    name: "Pneumatic Hammer Force Strike",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 150,
    velocity: 95,
    temperature: 305,
    medium: "Steel Anvil",
    formulas: ["J = F_avg * Δt", "J = Δp = m * Δv"],
    explain: "Examines mechanical pressure spikes during microseconds of hammer anvil impact.",
    steps: "1. Pre-load high-density kinetic strike hammer.\n2. Release pneumatic ram onto flat steel.\n3. Plot microsecond pressure impact spikes.",
    theory: "Shorter contact contact times during elastic collisions yield massive force spikes for uniform momentum changes.",
    hint: "Reduce contact time values to watch peak collision force readings skyrocket.",
    conceptAnalysis: "Force is the derivative of momentum over time. Hard impacts release energy in compressed milliseconds, creating peak loads.",
    commonPitfall: "Assuming peak impact force matches static mechanical loads.",
    formulaConcept: "F_avg = (m * Δv) / Δt"
  },
  {
    id: "gyro_spin",
    name: "Gyroscope Angular Momentum preservation",
    category: "Mechanics",
    template: "orbit",
    gravity: 9.8,
    mass: 75,
    velocity: 110,
    temperature: 293,
    medium: "Low Friction Pins",
    formulas: ["L = I * ω", "Torque = dL / dt (Precession)"],
    explain: "Simulates rotation mechanics of balanced brass flywheels under torque-induced precession regimes.",
    steps: "1. Actuate high-speed rotor angular slide.\n2. Apply localized cross-axis gravity load.\n3. Track rotational direction vector changes.",
    theory: "Rotor angular momentum vectors resist changes, resolving external angular forces into sideways gyroscopic precession steps.",
    hint: "Hike flywheel rotation velocity to stiffen angular persistence parameters.",
    conceptAnalysis: "Angular momentum is a conserved directional vector. External torques generate vector outputs perpendicular to both load and rotation axes.",
    commonPitfall: "Failing to account for wheel mass distribution boundaries when calculating inertia constants (I).",
    formulaConcept: "Ω_precession = (m * g * r) / (I * ω)"
  },
  {
    id: "pulley_atwood",
    name: "Atwood Dual Balance Machine",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 110,
    velocity: 20,
    temperature: 290,
    medium: "Braided Nylon cord",
    formulas: ["a = g * (m2 - m1) / (m1 + m2)", "T = 2 * g * m1 * m2 / (m1 + m2)"],
    explain: "Classic dual-load pulley rig tracking tension and gravitational accelerations under varying weight mismatches.",
    steps: "1. Mount two dissimilar mass nodes on string loop.\n2. Release locks, starting vertical flight arcs.\n3. Chart steady linear acceleration vectors.",
    theory: "The heavier weight drives descent, constrained by the inertial resistance summing from both mass elements.",
    hint: "Equalize dual weight metrics to bring the dynamic platform to idle homeostasis.",
    conceptAnalysis: "Net driving force matches differences in local weight vectors. Inertia parameters scale based on the system's total aggregated mass.",
    commonPitfall: "Believing tension equals the driving weight of the static heavier load.",
    formulaConcept: "T_tension = m1 * (g + a)"
  },
  {
    id: "drag_dense",
    name: "Submarine Drag in Heavy Fluid",
    category: "Mechanics",
    template: "projectile",
    gravity: 9.8,
    mass: 130,
    velocity: 15,
    temperature: 280,
    medium: "Saline Deep Sea water",
    formulas: ["Fd = 0.5 * ρ * v² * Cd * A", "P = Fd * v (Power consumption)"],
    explain: "Measures hydrodynamic power bounds required to overcome dynamic drag inside saline fluids.",
    steps: "1. Submerge stream profile in heavy water.\n2. Apply forward thruster configurations.\n3. Measure power curve requirements.",
    theory: "Dense mediums trigger turbulent skin friction boundaries, matching power consumption requirements with the cube of speed.",
    hint: "Double travel speeds to observe massive spikes in energy outputs.",
    conceptAnalysis: "Fluid mass density requires high energy to displace, leading to steep resistance gradients at top speeds.",
    commonPitfall: "Expecting speed parameters to scale linearly with engine power inputs.",
    formulaConcept: "P_required = k * ρ * v³"
  },
  {
    id: "spring_damp",
    name: "Damped Harmonic Oscillation test",
    category: "Mechanics",
    template: "wave",
    gravity: 9.8,
    mass: 55,
    velocity: 45,
    temperature: 293,
    medium: "Viscous Silicone Oil",
    formulas: ["F_spring = -k * x", "F_damping = -b * dx/dt"],
    explain: "Simulates spring-loaded mass tracking decay curves inside viscous shock-absorbing media.",
    steps: "1. Displace heavy spring from resting node.\n2. Release into viscous silicone oils.\n3. Plot classical exponential sinusoidal decay curves.",
    theory: "Restoring spring forces pull mass towards center, while silicone shear resistances sap energy velocity.",
    hint: "Lower fluid viscosity parameters to prolong spring oscillation lifetimes.",
    conceptAnalysis: "Mechanical kinetic potentials shift between spring tension and mass motion, dampening continuous cycles into heat.",
    commonPitfall: "Confusing underdamped decays with critical or overdamped movement profiles.",
    formulaConcept: "x(t) = A * e^(-γt) * cos(ωt)"
  },

  // SECTION 2: SPACE & REL (12 presets)
  {
    id: "orb_jupiter",
    name: "Jupiter Gravity Orbit Path",
    category: "Space & Rel",
    template: "orbit",
    gravity: 24.79,
    mass: 85,
    velocity: 80,
    temperature: 165,
    medium: "Hydrogen Gas halo",
    formulas: ["F_grav = G*M*m/r²", "v_circ = sqrt(G*M/r)"],
    explain: "High-gravity orbital mechanics tracking satellite trajectory in outer gas environments under 24.79 m/s².",
    steps: "1. Place sub-satellite at radial distance.\n2. Inject fast transverse velocity.\n3. Monitor circular orbit under extreme gravitational pull.",
    theory: "Circular paths require centrifugal forces to balance planetary gravitational pulls at specific altitudes.",
    hint: "Lower velocity to watch orbital satellite decay into Jovian clouds.",
    conceptAnalysis: "Extreme planet gravity yields monumental orbital speeds, compressing orbit schedules down to tiny cycles.",
    commonPitfall: "Neglecting the massive kinetic velocity needed to avoid gravitational collapse.",
    formulaConcept: "v_orbit = sqrt(24.79 * r)"
  },
  {
    id: "orb_black_hole",
    name: "Black Hole Gravitational Boundary",
    category: "Space & Rel",
    template: "orbit",
    gravity: 28.0,
    mass: 145,
    velocity: 125,
    temperature: 3,
    medium: "Relativistic Vacuum",
    formulas: ["r_s = 2*G*M / c²", "t_prime = t * sqrt(1 - r_s/r)"],
    explain: "Relativistic orbit mapping near event horizons under extreme Schwarzschild coordinates.",
    steps: "1. Approach gravitational boundary radius limit.\n2. Activate relativistic orbital velocity.\n3. Track extreme spatial path curvatures.",
    theory: "Gravitational tensors warp local spacetime coordinates, shifting orbital paths away from classical Kepler loops.",
    hint: "Enter coordinates close to gravity well to check time dilation factors.",
    conceptAnalysis: "Spacetime warp slows decay clocks near boundary limits, turning orbits into infinite temporal loops.",
    commonPitfall: "Using Newtonian mechanics models near massive critical star cores.",
    formulaConcept: "Time_Dilation = 1 / sqrt(1 - 2GM/rc²)"
  },
  {
    id: "kepler_three",
    name: "Kepler Third Law Orbit Calibration",
    category: "Space & Rel",
    template: "orbit",
    gravity: 10.5,
    mass: 55,
    velocity: 52,
    temperature: 5,
    medium: "Deep Space Vacuum",
    formulas: ["T² = (4*π² / G*M) * a³"],
    explain: "Verifies the direct mathematical link between orbital periods and semi-major ellipse axis spans.",
    steps: "1. Position stellar satellite on wide eccentric paths.\n2. Complete full solar orbital circuit.\n3. Confirm period harmonic values.",
    theory: "Gravitational decay profiles scale inversely with distance squared, syncing system speed constraints with Kepler limits.",
    hint: "Enlarge orbital radiuses to monitor period metrics lengthening.",
    conceptAnalysis: "Inner orbits speed up under proximity peaks, while distant tracks exhibit cold, lazy orbital sweeps.",
    commonPitfall: "Assuming satellite mass modifies orbital period curves in a 2-body system.",
    formulaConcept: "T = k * a^1.5"
  },
  {
    id: "low_earth_orbit",
    name: "Low Earth Orbit (LEO) Decay",
    category: "Space & Rel",
    template: "orbit",
    gravity: 9.8,
    mass: 30,
    velocity: 78,
    temperature: 280,
    medium: "Thermospheric drag tail",
    formulas: ["v = sqrt(G*Me / r)", "E = -G * Me * m / 2r"],
    explain: "Tracks satellite progress inside thin thermosphere edges where minor gas molecules sap kinetic power.",
    steps: "1. Launch satellite into low-altitude orbit.\n2. Step times forward to track atmospheric friction.\n3. Plot altitude dropping into decay spirals.",
    theory: "Friction drains orbital kinetic reserves, prompting LEO satellites to drop into denser gas layers.",
    hint: "Set mass lower to watch drag spiral altitude decays accelerate.",
    conceptAnalysis: "Dropping orbits shift potential energies into kinetic speeds, accelerating speed averages even as friction increases.",
    commonPitfall: "Thinking atmospheric drag immediately slows LEO speeds down (it actually speeds them up as they drop).",
    formulaConcept: "da/dt = -2 * (Fd / m) * a"
  },
  {
    id: "lagrange_l1",
    name: "Lagrange L1 Saddlepoint stability",
    category: "Space & Rel",
    template: "orbit",
    gravity: 15.0,
    mass: 45,
    velocity: 40,
    temperature: 15,
    medium: "Solar wind vacuum",
    formulas: ["F_eff = F_grav1 + F_grav2 - F_centrifugal", "dU/dx = 0 (equilibrium)"],
    explain: "Simulates gravity balancing tricks at L1 positions directly between two massive solar bodies.",
    steps: "1. Input payload precisely at dual-gravity saddlepoint.\n2. Track gravitational forces balanced.",
    theory: "Lagrange parameters represent coordinate spots where two physical masses coordinate gravity pulls to lock orbit schedules.",
    hint: "Trigger slight directional pushes to watch unstable saddle systems peel away.",
    conceptAnalysis: "L1 saddle-points balance gravity pulls, but remain unstable along Sun-Earth axes, requiring thruster corrections.",
    commonPitfall: "Believing L1 is fully stable without active station-keeping maneuvers.",
    formulaConcept: "x_L1 ≈ R * (1 - (M2 / 3M1)^(1/3))"
  },
  {
    id: "retrograde_orbit",
    name: "Retrograde Satellite Orbit",
    category: "Space & Rel",
    template: "orbit",
    gravity: 9.8,
    mass: 50,
    velocity: -75,
    temperature: 250,
    medium: "Interstellar vacuum",
    formulas: ["L = r x p (negative)", "E = 0.5*m*v² - G*M*m/r"],
    explain: "Runs orbital models tracking clock-wise trajectories in opposition to planetary rotation directions.",
    steps: "1. Engage reverse launcher vector paths.\n2. Confirm stable counter-orbit circles.\n3. Measure satellite relative velocity offsets.",
    theory: "While backward orbits stay structurally stable, launching them consumes massive fuel to reverse native planet spins.",
    hint: "Compare relative collision velocities against prograde tracking satellites.",
    conceptAnalysis: "Orbital flight physics operates neutrally, remaining uniform regardless of co-rotation or contrarian spins.",
    commonPitfall: "Assuming counter rotation affects gravitational stability constants.",
    formulaConcept: "L_vec = -(r * m * v_trans)"
  },
  {
    id: "mercury_precess",
    name: "Mercury Perihelion Precession",
    category: "Space & Rel",
    template: "orbit",
    gravity: 28.0,
    mass: 80,
    velocity: 95,
    temperature: 440,
    medium: "Solar plasma field",
    formulas: ["Δθ = 24 * π³ * a² / (T² * c² * (1 - e²))"],
    explain: "Tracks tiny shifts in perihelion pathways under relativistic coordinates.",
    steps: "1. Track highly eccentric elliptical orbits.\n2. Mark location of closest approach (perihelion).\n3. Plot precession angles repeating.",
    theory: "Gravitational warping at perihelion proximity fields creates tiny shifts in orbital axes.",
    hint: "Increase stellar core density values to amplify precession rates.",
    conceptAnalysis: "Relativistic effects add a small 1/r³ pull term, causing Kepler ellipses to slowly precess over time.",
    commonPitfall: "Using purely Newtonian physics equations to calculate orbital anomalies.",
    formulaConcept: "U_gr = -G*M/r - (G*M*L²)/(c²*r³)"
  },
  {
    id: "tidal_roche",
    name: "Roche Limit Stellar Disruption",
    category: "Space & Rel",
    template: "orbit",
    gravity: 24.0,
    mass: 90,
    velocity: 82,
    temperature: 600,
    medium: "Space vacuum",
    formulas: ["d_roche = R_primary * (2 * ρ_M / ρ_m)^(1/3)"],
    explain: "Simulates tidal shear stress pulling moon structures apart near massive planets.",
    steps: "1. Guide moon probe below Roche limit zone.\n2. Witness differential gravitational forces.\n3. Track fragmentation into planetary rings.",
    theory: "Roche thresholds specify critical radii where planet tidal pulls overpower moon internal binding forces.",
    hint: "Decrease moon mass densities to watch tidal disintegration happen at wider radii.",
    conceptAnalysis: "Gravitational gradients across moon diameters generate tension, dismantling structures when tensile bounds break.",
    commonPitfall: "Confusing orbital collision decay crashes with physical Roche tidal disintegration.",
    formulaConcept: "F_tidal = (2 * G * M * r * Δr) / d³"
  },
  {
    id: "einstein_lens",
    name: "Einstein Light Bending warped arc",
    category: "Space & Rel",
    template: "projectile",
    gravity: 28.0,
    mass: 1, // photon mass-like unit
    velocity: 150, // simulated lightspeed scaling
    temperature: 3,
    medium: "Lensed Spacetime",
    formulas: ["θ_bend = 4 * G * M / (r * c²)"],
    explain: "Models coordinate shifts of photon paths traversing near hyper-dense gravity wells.",
    steps: "1. Direct light rays towards a massive star.\n2. Measure ray bending angles on flyby.\n3. Plot Einstein rings and twin visual focal arcs.",
    theory: "Mass warps spacetime geometry, forcing straight photon null-geodesic lines to curve.",
    hint: "Guide light rays closer to the dark object to widen lensing angles.",
    conceptAnalysis: "Photons possess zero rest mass, yet follow warped gravitational paths, magnifying distant background galaxies.",
    commonPitfall: "Calculating lensing bends using Newtonian escape deflection equations (which are 50% too skimpy).",
    formulaConcept: "θ = (4 * G * M) / (b * c²)"
  },
  {
    id: "schwarzschild_capture",
    name: "Schwarzschild Photon Capture Sphere",
    category: "Space & Rel",
    template: "orbit",
    gravity: 28.0,
    mass: 2,
    velocity: 145,
    temperature: 2,
    medium: "Singularity throat",
    formulas: ["r_photon = 3 * G * M / c²"],
    explain: "Calculates unstable orbits of light rays bound at 1.5x Schwarzschild radii around black holes.",
    steps: "1. Position photon tangent to star horizon.\n2. Launch light speed simulation loops.\n3. Track unstable orbit rings or paths.",
    theory: "At 1.5 Rs, gravity orbits light rays, but tiny pushes cause them to plunge inside or escape.",
    hint: "Steer velocity inputs slightly off-balance to watch immediate captures or wide escapes.",
    conceptAnalysis: "Extreme star wells hold physical light rays in circle orbits. This photon sphere is the ultimate cosmic mirror.",
    commonPitfall: "Expecting stable, self-correcting orbital rings at active photon spheres.",
    formulaConcept: "r_sphere = 1.5 * r_s"
  },
  {
    id: "tidal_flare",
    name: "Milky Way Tidal Flare",
    category: "Space & Rel",
    template: "orbit",
    gravity: 25.0,
    mass: 120,
    velocity: 95,
    temperature: 1500,
    medium: "Interstellar ionized gas",
    formulas: ["F_differential = 2*G*M*r/d³"],
    explain: "Simulates galactic gas accretion rings colliding near central supermassive black hole zones.",
    steps: "1. Direct interstellar gas into accretion loops.\n2. Trace differential energy accelerations.\n3. Observe glowing flare spikes near peak approach.",
    theory: "Strong gravity fields warp accretion rings, releasing energy spikes during tidal disruptions.",
    hint: "Adjust mass ranges to modify tidal heating parameters.",
    conceptAnalysis: "Gravitational forces sheer matter into ionized streams, converting gravitational energy into thermal light.",
    commonPitfall: "Assuming uniform velocities across gas ring diameters.",
    formulaConcept: "T_disk ≈ (3*G*M_bh*M_dot / (8*π*σ*r³))^(0.25)"
  },
  {
    id: "mars_rover_drop",
    name: "Mars Gravity Rover Drop",
    category: "Space & Rel",
    template: "projectile",
    gravity: 3.71,
    mass: 110,
    velocity: 18,
    temperature: 220,
    medium: "Thin CO₂ layer",
    formulas: ["v_impact = sqrt(v0² + 2*g*h)"],
    explain: "Simulates sky-crane rover balance speeds in Martian gravity fields under 3.71 m/s².",
    steps: "1. Release landing module from hovering cran.\n2. Control retro-rocket balance thrust.\n3. Perform smooth touchdown trials.",
    theory: "Martian gravity is roughly 38% of Earth's, which reduces landing impact loads.",
    hint: "Vary thruster ignition times to achieve touchdown speeds under 2 m/s.",
    conceptAnalysis: "Low gravity and thin air require active propulsion, as parachutes alone cannot guarantee soft landings.",
    commonPitfall: "Expecting thick atmosphere resistance curves to assist Rover descents.",
    formulaConcept: "a_net = g_mars - (F_thrust / m)"
  },

  // SECTION 3: WAVES & SOUND (12 presets)
  {
    id: "wave_pipe",
    name: "Fluid Flow in Pipe Velocity",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 45,
    velocity: 25,
    temperature: 288,
    medium: "Water Fluid",
    formulas: ["Q = A1 * v1 = A2 * v2", "P1 + 0.5*ρ*v1² = Constant"],
    explain: "Bernoulli fluid stream assessment monitoring pipeline velocity transitions and pressure gradients.",
    steps: "1. Pump water flow into constriction blocks.\n2. Chart wave pressure curves.\n3. Measure velocity speedups in narrow sections.",
    theory: "Constricting pipe widths accelerates fluid speeds to maintain uniform mass flow conservation.",
    hint: "Increase velocity slider to check water hammer pressures.",
    conceptAnalysis: "Venturi shifts convert potential fluid pressures into kinetic speed vectors, reducing pressure in fast channels.",
    commonPitfall: "Formulating that narrowing pipes increases fluid pressures (it dramatically decreases pressure).",
    formulaConcept: "P_drop = 0.5 * ρ * (v2² - v1²)"
  },
  {
    id: "wave_interfere",
    name: "Wave Interference Fields",
    category: "Waves & Sound",
    template: "wave",
    gravity: 15.0,
    mass: 50,
    velocity: 45,
    temperature: 290,
    medium: "Fluid surface",
    formulas: ["y_res = y1 * sin(kx - wt) + y2 * sin(...)"],
    explain: "Interference mechanics showing wave constructive peaks and destructive null zones.",
    steps: "1. Actuate two wave emitters simultaneously.\n2. Track crest collisions.\n3. Observe constructive addition and destructive cancellations.",
    theory: "Superposition allows phase waves to add up linearly or cancel out.",
    hint: "Slide mass scales to alter mechanical wave amplitudes.",
    conceptAnalysis: "Waves in sequence sum their displacement values, creating high energy arcs at in-phase intersections.",
    commonPitfall: "Believing wave energy gets lost during destructive cancellation (it simply shifts to adjacent sections).",
    formulaConcept: "I_max = (A1 + A2)²"
  },
  {
    id: "doppler",
    name: "Doppler Shift Sound velocity",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 30,
    velocity: 90,
    temperature: 293,
    medium: "Standard Air",
    formulas: ["f_obs = f_src * (v_snd / (v_snd - v_src))"],
    explain: "Simulates wave frequency compressions as emitters accelerate towards observers.",
    steps: "1. Actuate sound waves from constant emitter.\n2. Accelerate emitter forward close to Mach speeds.\n3. Observe wave crowding ahead.",
    theory: "Relative speeds compress physical wavelengths ahead of sound sources, shifting observed pitches.",
    hint: "Slide velocity parameters to watch wave convergence patterns.",
    conceptAnalysis: "Approaching sources pack wave cycles closer together, raising observed pitch, then stretching them to lower pitches upon passing.",
    commonPitfall: "Expecting pitch to continuously climb as sources approach at constant speed.",
    formulaConcept: "λ_prime = (v_snd - v_src) / f_src"
  },
  {
    id: "standing_harmonics",
    name: "Standing String Welds",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 25,
    velocity: 60,
    temperature: 295,
    medium: "Elastomer Cord",
    formulas: ["f_n = n * v / (2 * L)", "v = sqrt(Tension / linear_density)"],
    explain: "Produces harmonic resonance nodes on locked-end vibratory strings.",
    steps: "1. Anchor string ends tightly under load.\n2. Trigger harmonic drive vibrations.\n3. Count nodes (still points) and antinodes (peak swings).",
    theory: "Reflected waves interfere constructively at resonance frequencies, locking waves in vertical patterns.",
    hint: "Vary velocity inputs to cycle through 1st, 2nd, and 3rd harmonics.",
    conceptAnalysis: "Tension and density determine wave travel speeds, setting the specific resonance frequencies for fixed-length strings.",
    commonPitfall: "Believing string tension modifies overall standing wave nodes directly without altering speed.",
    formulaConcept: "λ_n = 2 * L / n"
  },
  {
    id: "pascal_liquid",
    name: "Pascal Fluid Hydraulic Press",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 120,
    velocity: 15,
    temperature: 290,
    medium: "Mineral Oil",
    formulas: ["P = F1 / A1 = F2 / A2", "Work = F1 * d1 = F2 * d2"],
    explain: "Demonstrates mechanical advantage scaling inside sealed hydraulic brake structures.",
    steps: "1. Exert pilot force on small cylinder piston.\n2. Track uniform pressure propagation.\n3. Lift massive heavy-load pistons.",
    theory: "Applied pressure inside sealed fluids distributes evenly to all boundaries without losses.",
    hint: "Increase mass settings to see maximum lifting capacity limits.",
    conceptAnalysis: "Hydraulic platforms trade travel distance for output force, keeping overall mechanical work input conserved.",
    commonPitfall: "Believing hydraulic presses generate extra work energy (force increases but distance drops proportionately).",
    formulaConcept: "F2 = F1 * (A2 / A1)"
  },
  {
    id: "seismic_p_wave",
    name: "Earthquake Seismic P-Wave speed",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 85,
    velocity: 105,
    temperature: 420,
    medium: "Granite Crust",
    formulas: ["v_p = sqrt((K + 4G/3) / ρ)"],
    explain: "Simulates high-speed solid-rock pressure waves during fault rupture displacements.",
    steps: "1. Trigger tectonic fault slips.\n2. Track fast longitudinal compression waves.\n3. Plot arrival times at distant seismographs.",
    theory: "Compression P-waves travel fastest through crust rocks, using bulk modular spring rebounds.",
    hint: "Raise medium elasticity settings to watch primary seismic waves speed up.",
    conceptAnalysis: "Stiff solid materials rebound rapidly when compressed, enabling fast wave propagation compared to soft sands.",
    commonPitfall: "Confusing compressional primary waves with slower transverse shear (S) waves.",
    formulaConcept: "v_p = sqrt(Elastic_Modulus / Density)"
  },
  {
    id: "sound_barrier_rupture",
    name: "Supersonic Sonic Boom cone",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 40,
    velocity: 140, // trans-sonic velocity
    temperature: 275,
    medium: "Altitude Air density",
    formulas: ["sin(θ) = v_sound / v_source"],
    explain: "Generates overlapping wave barrier hulls at supersonic travel speeds.",
    steps: "1. Push aircraft speed target past local Mach thresholds.\n2. Watch wave overlays pile up.\n3. Plot trailing conical shock wavefronts.",
    theory: "When emitters outrun their sound, soundwaves blend into high-energy conical shock corridors.",
    hint: "Increase velocity above 120 to compress shock cones tightly.",
    conceptAnalysis: "Supersonic travel piles sound wave vectors into physical pressure boundaries, releasing explosive sonic boom peaks.",
    commonPitfall: "Assuming sonic booms only trigger right at the moment of Mach transition.",
    formulaConcept: "Mach_Number = v_source / v_sound"
  },
  {
    id: "ocean_soliton",
    name: "Tsunami Ocean Soliton wave",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 95,
    velocity: 85,
    temperature: 285,
    medium: "Shallow Ocean shelf",
    formulas: ["v = sqrt(g * (d + H))", "η(x,t) = a * sech²(k*(x - c*t))"],
    explain: "Models isolated, self-reinforcing wave crests traversing ocean shelves without dispersion.",
    steps: "1. Inject deep mechanical ocean shocks.\n2. Form stable isolated soliton waves.\n3. Track speed retention across shallow basins.",
    theory: "Soliton waves combine non-linear steepening and channel dispersion to maintain stable wave shapes.",
    hint: "Increase gravity settings to watch ocean soliton speeds climb.",
    conceptAnalysis: "Non-linear wave additions keep energy compressed in single channels, allowing waves to cross ocean basins intact.",
    commonPitfall: "Expecting ocean solitons to dissipate energy like standard sine waves.",
    formulaConcept: "c_soliton = sqrt(g * depth)"
  },
  {
    id: "organ_pipe_resonance",
    name: "Organ Pipe Acoustic Resonance",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 15,
    velocity: 35,
    temperature: 293,
    medium: "Internal Dry Air",
    formulas: ["f = n * v / (4 * L) (closed ok)"],
    explain: "Acoustic assessment of standing soundwaves inside half-open air tubes.",
    steps: "1. Blow air across organ pipe inputs.\n2. Establish acoustic pressure boundaries.\n3. Measure harmonic resonance frequencies.",
    theory: "Locked tube ends force zero air movement, while open ends permit maximum wave speed swings.",
    hint: "Raise air temperatures to watch fundamental pitches sharpen.",
    conceptAnalysis: "Air temperature changes change sound travel velocities, shifting musical pitches higher on hot days.",
    commonPitfall: "Believing closed organ pipes contain the same harmonic series as open conduits.",
    formulaConcept: "f_fundamental = v_sound / (4 * L)"
  },
  {
    id: "acoustic_levitate",
    name: "Acoustic Levitation nodes",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 10,
    velocity: 50,
    temperature: 295,
    medium: "Kilohertz Transducers",
    formulas: ["P_acoustic = P0 * sin(kx) * cos(wt)"],
    explain: "Calculates sound wave pressure wells capable of suspending small water droplets.",
    steps: "1. Fire opposed ultrasonic transducer heads.\n2. Form standing wave pressure fields.\n3. Suspend small test droplets inside static node locations.",
    theory: "Standing waves contain pressure valleys where force climbs match downward gravitational weight.",
    hint: "Calibrate frequency arrays to hold heavier mass nodes securely.",
    conceptAnalysis: "Levitation succeeds because ultrasonic energy matches gravitational force vectors, trapping items in steady positions.",
    commonPitfall: "Thinking acoustic levitation operates on magnetic attraction currents.",
    formulaConcept: "F_acoustic = -V_drop * ∇(P²_avg) / (4*ρ*c²)"
  },
  {
    id: "doppler_redshift",
    name: "Relativistic Cosmological Redshift",
    category: "Waves & Sound",
    template: "wave",
    gravity: 12.0,
    mass: 5,
    velocity: 110,
    temperature: 10,
    medium: "Cosmic expansion vacuum",
    formulas: ["1 + z = sqrt((1 + v/c) / (1 - v/c))"],
    explain: "Models light wavelength stretching as distant galaxies recede at relativistic speeds.",
    steps: "1. Actuate light waves from receding stellar source.\n2. Accelerate galaxy speed towards light barrier.\n3. Map shift from blue wavelengths into infrared.",
    theory: "Expanding space stretches traveling light wavelengths, shifting color spectrum profiles.",
    hint: "Increase recession speeds to shift visible wavelengths into infrared.",
    conceptAnalysis: "Cosmic expansion stretches traveling photons, lowering energy levels and shifting spectra toward reddish frequencies.",
    commonPitfall: "Attributing galactic redshifts purely to physical motion rather than expanding spacetime.",
    formulaConcept: "z_shift = (λ_observed - λ_emitted) / λ_emitted"
  },
  {
    id: "ultrasonic_echo",
    name: "Ultrasonic Material Flaw scanner",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 30,
    velocity: 70,
    temperature: 290,
    medium: "Cast Iron slab",
    formulas: ["d = v * Δt / 2"],
    explain: "Simulates ultrasound echo scanners locating defects inside metal blocks.",
    steps: "1. Emit high-frequency sound pulses into steel.\n2. Reflect pulses from crack anomalies.\n3. Measure echo return times to determine defect depth.",
    theory: "Material density boundaries reflect acoustic energy, mapping internal flaws based on return delays.",
    hint: "Double material thickness to watch return echo times double.",
    conceptAnalysis: "Acoustic impedance anomalies bounce wave energy, revealing interior cracks without physical dismantling.",
    commonPitfall: "Neglecting round-trip travel when calculating distance coordinates.",
    formulaConcept: "Thickness = (v_steel * t_delay) / 2"
  },

  // SECTION 4: QUANTUM & FIELDS (12 presets)
  {
    id: "schr_wave",
    name: "Schrödinger Probability Wave",
    category: "Quantum & Fields",
    template: "wave",
    gravity: 5.0,
    mass: 12,
    velocity: 95,
    temperature: 4,
    medium: "Cryo quantum tube",
    formulas: ["i*hbar * dΨ/dt = H * Ψ", "P(x) = |Ψ(x)|²"],
    explain: "Quantum wave-function tracking probability clouds of trapped electrons in potential wells.",
    steps: "1. Trap slow electron inside narrow boundary walls.\n2. Actuate quantum state wave function.\n3. Plot probability peaks (standing waves) across the well.",
    theory: "Particles exist as probability waves until measurements collapse them into specific positions.",
    hint: "Lower system temperature to collapse state noise, clarifying quantum peaks.",
    conceptAnalysis: "Confined electrons resemble standing guitar-string waves, restricting energy levels to precise steps.",
    commonPitfall: "Expecting particles to flow in classical paths within subatomic spaces.",
    formulaConcept: "E_n = (n² * h² * π²) / (2 * m * L²)"
  },
  {
    id: "elec_field",
    name: "Electrostatic Field Repulsion",
    category: "Quantum & Fields",
    template: "orbit",
    gravity: 8.0,
    mass: 35,
    velocity: 70,
    temperature: 293,
    medium: "Charged Helium gas",
    formulas: ["F_coulomb = k_e * q1 * q2 / r²", "E_field = F / q"],
    explain: "Coulomb repulsion tracking electrostatic orbital paths of same-charge particles.",
    steps: "1. Position central fixed charge.\n2. Inject similar-sign charge at speed.\n3. Observe hyperbola scattering trajectories.",
    theory: "Matching charges repel with forces inversely proportional to distance squared, mimicking gravity wells in reverse.",
    hint: "Increase charge mass limits to watch deflection paths straighten.",
    conceptAnalysis: "Repelling field force curves paths into hyperbolas, acting as a spatial barrier that keeps charges apart.",
    commonPitfall: "Believing electrostatic deflected paths accelerate indefinitely without energy sources.",
    formulaConcept: "V_potential = k_e * q / r"
  },
  {
    id: "mag_field",
    name: "Magnetic Field Lorentz Force",
    category: "Quantum & Fields",
    template: "orbit",
    gravity: 4.5,
    mass: 40,
    velocity: 85,
    temperature: 298,
    medium: "Helium Chamber",
    formulas: ["F_lorentz = q * (v x B)"],
    explain: "Simulates helical orbit coordinates of charged ion streams within uniform magnetic fields.",
    steps: "1. Inject ion stream into active magnetic field chamber.\n2. Observe Lorentz forces bending paths into loops.\n3. Measure orbit radiuses.",
    theory: "Magnetic forces act perpendicular to both speed and field lines, creating circular paths without affecting particle energy.",
    hint: "Increase speed to widen bend radiuses in simulated fields.",
    conceptAnalysis: "Lorentz fields bend charge vectors into precise circles, sorting particles based on mass-to-charge ratios.",
    commonPitfall: "Believing static magnetic fields accelerate stationery charges (velocity must be non-zero).",
    formulaConcept: "r_cyclotron = (m * v) / (q * B)"
  },
  {
    id: "gold_foil",
    name: "Rutherford Alpha Deflection",
    category: "Quantum & Fields",
    template: "projectile",
    gravity: 12.0,
    mass: 50,
    velocity: 110,
    temperature: 293,
    medium: "Auric Crystal foil",
    formulas: ["b = (z * Z * e²) / (2 * π * ε0 * m * v² * tan(θ/2))"],
    explain: "Recreates Rutherford's alpha particle trials, revealing dense atomic nuclear cores.",
    steps: "1. Fire high-speed helium nuclei at gold atoms.\n2. Map scattering angles of incoming beams.\n3. Observe rare sharp bounces.",
    theory: "Sharp deflects prove atomic mass is packed within a tiny central nucleus, bypassing empty electron clouds.",
    hint: "Slow particle velocities to amplify repulsion scattering angles.",
    conceptAnalysis: "Direct trajectory hits experience massive electrostatic repulsion forces, bouncing alpha particles straight backward.",
    commonPitfall: "Attributing sharp bounces to collisions with lighter orbiting electrons.",
    formulaConcept: "Scattering_Probability ∝ 1 / sin⁴(θ/2)"
  },
  {
    id: "zeeman_split",
    name: "Zeeman Spectral Splitting",
    category: "Quantum & Fields",
    template: "wave",
    gravity: 9.8,
    mass: 30,
    temperature: 400,
    velocity: 45,
    medium: "Magnetic Sodium vapor",
    formulas: ["ΔE_zeeman = g_l * μ_B * B * m_j"],
    explain: "Models spectral line splitting under powerful external magnetic fields.",
    steps: "1. Ignite glowing sodium gas vapor clouds.\n2. Introduce high magnetic flux levels.\n3. Orbit singular spectral outputs into triplet line arrays.",
    theory: "Magnetic fields lift quantum energy state degeneracies, splitting electron energy levels.",
    hint: "Vary magnetic field strength to alter splitting widths.",
    conceptAnalysis: "Spin-orbital alignments shift in magnetic fields, dividing single energy emissions into distinct spectral bands.",
    commonPitfall: "Assuming Zeeman splits happen without external magnetic influence.",
    formulaConcept: "Δν = e * B / (4 * π * m_e)"
  },
  {
    id: "supercond_lift",
    name: "Meissner Effect Magnetic suspension",
    category: "Quantum & Fields",
    template: "orbit",
    gravity: 9.8,
    mass: 65,
    velocity: 30,
    temperature: 70, // liquid nitrogen temp equivalent
    medium: "Ceramic YBCO pellet",
    formulas: ["B_interior = 0 (perfect diamagnetism)", "F_lev = -∇(E_magnetic)"],
    explain: "Simulates magnetic field exclusion that enables zero-friction track levitation.",
    steps: "1. Cool ceramic pellets below critical temperatures.\n2. Place permanent magnet above pellets.\n3. Levitate pellet in stable, locked alignment.",
    theory: "Superconductors expel interior magnetic fields, locking fields to float magnets in space.",
    hint: "Warm pellets out of superconducting states to drop magnets immediately.",
    conceptAnalysis: "Zero resistance creates instant mirror currents that block incoming magnetic fields, achieving stable levitation.",
    commonPitfall: "Confusing Meissner suspension with simple magnetic repulsion.",
    formulaConcept: "λ_london = sqrt(m_e / (μ0 * n * e²))"
  },
  {
    id: "photo_electric",
    name: "Photoelectric Work Energy threshold",
    category: "Quantum & Fields",
    template: "projectile",
    gravity: 9.8,
    mass: 1, // electron
    velocity: 80,
    temperature: 298,
    medium: "Cesium Cathode plate",
    formulas: ["E_kinetic = h * f - Phi_work"],
    explain: "Measures electron emission from metal surfaces struck by light rays of varying frequencies.",
    steps: "1. Shine low-frequency light onto plate.\n2. Gradually raise light frequencies past threshold bounds.\n3. Measure emitted electron velocity.",
    theory: "Light deposits energy as packet photons, releasing electrons only if single photon energy beats work functions.",
    hint: "Raise light frequency past cesium work functions to launch active electron flows.",
    conceptAnalysis: "Electron escape speed tracks light frequency rather than brightness. Brighter light simply yields more electrons.",
    commonPitfall: "Expecting high-brightness low-frequency light to eventually release electrons (it never does).",
    formulaConcept: "f_threshold = Phi_work / h"
  },
  {
    id: "hall_effect",
    name: "Hall Voltage conductor deflection",
    category: "Quantum & Fields",
    template: "projectile",
    gravity: 9.8,
    mass: 15,
    velocity: 42,
    temperature: 300,
    medium: "Doped Silicon slab",
    formulas: ["V_hall = I_current * B_field / (n * e * thickness)"],
    explain: "Generates transverse voltage as magnetic fields push active currents sideways inside conductors.",
    steps: "1. Drive stable current through test conductors.\n2. Apply magnetic fields perpendicular to current paths.\n3. Measure transverse Hall potential differences.",
    theory: "Lorentz forces deflect moving electrons to one side, forming electric fields that balance magnetic push.",
    hint: "Reverse magnetic fields to flip observed voltage polarities.",
    conceptAnalysis: "Side-pushed electrons build up lateral charges, creating readable voltages that reveal charge-carrier types.",
    commonPitfall: "Believing Hall voltages appear when currents are zero or magnetic fields are parallel to flows.",
    formulaConcept: "E_hall = v_drift * B_field"
  },
  {
    id: "plasma_tokamak",
    name: "Tokamak Toroidal magnetic bottle",
    category: "Quantum & Fields",
    template: "orbit",
    gravity: 1.0, // weak gravitational frame
    mass: 25,
    velocity: 130,
    temperature: 150000, // super hot plasma
    medium: "Deuterium gas vacuum",
    formulas: ["F_gradB = -mu * ∇B", "v_drift = (v_perp² + 2*v_parallel²) * (R x B) / (2 * omega * R² * B)"],
    explain: "Confinds hot plasma loops within magnetic fields to mimic stellar fusion cores.",
    steps: "1. Inject deuterium gas into donut chambers.\n2. Rotate magnetic coils to shape helical fields.\n3. Confine hot gas without touch walls.",
    theory: "Helical magnetic lines trap charged plasma particles, preventing wall touches that quench reactions.",
    hint: "Boost magnetic field strength to compress plasma streams tightly.",
    conceptAnalysis: "Magnetic confinement keeps high-energy particles in circular paths, holding fusion heat inside magnetic walls.",
    commonPitfall: "Expecting plasma stability without helical field twists.",
    formulaConcept: "beta_ratio = P_plasma / (B² / 2μ0)"
  },
  {
    id: "compton_recoil",
    name: "Compton X-Ray Photon collision",
    category: "Quantum & Fields",
    template: "projectile",
    gravity: 9.8,
    mass: 20,
    velocity: 145, // lightspeed scaling
    temperature: 15,
    medium: "Graphite Block target",
    formulas: ["λ_prime - λ = (h / (m_e * c)) * (1 - cos(θ))"],
    explain: "Models energy transfers during X-ray photon collisions with free target electrons.",
    steps: "1. Fire high-energy X-ray photons at graphite carbon.\n2. Deflect incoming wave paths.\n3. Measure wavelength stretches and electron recoil speed.",
    theory: "Photons carry momentum as particles, losing energy and stretching wavelengths during electron impacts.",
    hint: "Increase deflection angles to maximize wavelength shifts.",
    conceptAnalysis: "Impact energy shifts into electron velocities, dropping photon frequencies and shifting wave colors.",
    commonPitfall: "Thinking Compton scattering keeps photon wavelengths unchanged.",
    formulaConcept: "p_photon = h / λ"
  },
  {
    id: "faraday_dyn",
    name: "Faraday Induction Loop generator",
    category: "Quantum & Fields",
    template: "wave",
    gravity: 9.8,
    mass: 55,
    velocity: 60,
    temperature: 295,
    medium: "Copper Wire coils",
    formulas: ["EMF = -N * dFlux / dt", "Flux = B * A * cos(θ)"],
    explain: "Generates electrical voltage by moving magnets through wire coils.",
    steps: "1. Slide permanent magnetic rod into copper coils.\n2. Track magnetic field variations.\n3. Measure induced voltage spikes.",
    theory: "Changing magnetic fields create circular electrical fields that drive currents in closed coils.",
    hint: "Increase travel speeds to produce higher voltage peaks.",
    conceptAnalysis: "Mechanical motion turns directly into electrical currents through magnetic flux changes.",
    commonPitfall: "Believing stationary magnets inside coils generate continuous voltage outputs.",
    formulaConcept: "EMF_max = N * B * A * ω"
  },
  {
    id: "schrodinger_tunneling",
    name: "Quantum Tunneling Probability",
    category: "Quantum & Fields",
    template: "wave",
    gravity: 3.0,
    mass: 8,
    velocity: 80,
    temperature: 5,
    medium: "Subatomic barrier",
    formulas: ["T ≈ e^(-2*K*L)", "K = sqrt(2*m*(U - E))/hbar"],
    explain: "Tracks particle probability waves passing through solid energy barriers.",
    steps: "1. Fire electron wave-packets at thin potential barriers.\n2. Observe wave reflections and barrier penetration.\n3. Track transmitted waves on other side.",
    theory: "Quantum pieces can bypass barriers if their probability waves extend through barrier widths.",
    hint: "Narrow barrier widths to boost tunneling success rates.",
    conceptAnalysis: "Wave functions decay exponentially inside barriers, but thin barrier walls allow waves to emerge intact.",
    commonPitfall: "Thinking particles acquire extra energy to jump over physical barriers.",
    formulaConcept: "T_probability = (1 + (U₀ * sin(k * L))² / (4 * E * (U₀ - E)))⁻¹"
  },

  // SECTION 5: THERMAL/FLUID (12 presets)
  {
    id: "gas_laws",
    name: "Gas Particle Expansion",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 12.0,
    mass: 60,
    velocity: 95,
    temperature: 380,
    medium: "Argon Gaseous phase",
    formulas: ["P * V = n * R * T", "KE_avg = 1.5 * k_B * T"],
    explain: "Kinetic-molecular theory tracker measuring pressure changes during gas volume variations.",
    steps: "1. Encapsulate gas sample in volume containers.\n2. Heat system to trigger energetic molecular vibration.\n3. Record pressure strikes.",
    theory: "Thermal energy fuels molecular speeds, multiplying wall collisions to increase pressure properties.",
    hint: "Lower volume settings to watch pressure readings spike.",
    conceptAnalysis: "Heat accelerates gas speed and collision rates, inflating container pressures.",
    commonPitfall: "Believing gas molecules stop moving at standard zero Celsius conditions.",
    formulaConcept: "v_rms = sqrt(3 * R * T / M)"
  },
  {
    id: "fluid_bernoulli",
    name: "Bernoulli Airfoil Lift pressure",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 55,
    velocity: 95,
    temperature: 288,
    medium: "Laminar Airflow",
    formulas: ["P + 0.5 * ρ * v² = Const", "Lift = L_coeff * 0.5 * ρ * v² * A"],
    explain: "Aviation test tracking pressure differences that generate upward lift forces over wings.",
    steps: "1. Blow air across curved wing profiles.\n2. Track fast air speeds over top sections.\n3. Record upward lift pressure.",
    theory: "Curved wings speed up top airflow, reducing top pressure and creating upward lift.",
    hint: "Increase velocity input to monitor wing lift trends.",
    conceptAnalysis: "Airspeed differences create pressure imbalances that push wings upward.",
    commonPitfall: "Attributing Lift purely to air striking flat bottom wing surfaces.",
    formulaConcept: "ΔP = 0.5 * ρ * (v_top² - v_bottom²)"
  },
  {
    id: "stefan_bolt",
    name: "Stefan-Boltzmann Radiation energy",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 75,
    velocity: 25,
    temperature: 873, // Glowing hot iron temperature
    medium: "Vacuum heater",
    formulas: ["P_radiate = e * sigma * A * T⁴"],
    explain: "Calculates thermal energy radiated from glowing blackbody surfaces across temperature ranges.",
    steps: "1. Heat metallic core plates to glowing hot temperatures.\n2. Measure infrared energy emitted.\n3. Plot energy spikes scaling with temperature.",
    theory: "Radiation outputs scale with the fourth power of temperature, making hot objects radiate energy rapidly.",
    hint: "Double absolute temperatures to watch radiation jump by exactly 16x.",
    conceptAnalysis: "Thermal vibrations accelerate charged particles, launching energy waves across space.",
    commonPitfall: "Assuming thermal radiation requires gas mediums to transfer energy.",
    formulaConcept: "E_flux = 5.67e-8 * T⁴"
  },
  {
    id: "conduction_bar",
    name: "Conduction Thermal Rod transfer",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 70,
    velocity: 12,
    temperature: 420, // hot side temperature
    medium: "Refined copper core",
    formulas: ["Q / dt = k * A * (Thot - Tcold) / Length"],
    explain: "Measures heat flow through copper bars linking warm heat sources to cold drains.",
    steps: "1. Heat one end of polished copper bars.\n2. Track thermal energy travel through bars.\n3. Note thermal balance at far ends.",
    theory: "Free electrons collide alongside vibrating atoms to transfer thermal energy through metal structures.",
    hint: "Use thicker rods to increase heat flow speeds.",
    conceptAnalysis: "Heat moves along temperature differences, flowing energy until rods reach uniform balance.",
    commonPitfall: "Expecting thermal conduction speeds to remain uniform across different materials like steel and copper.",
    formulaConcept: "R_thermal = Length / (k * A)"
  },
  {
    id: "brownian_motion",
    name: "Brownian Molecular Agitation",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 18,
    velocity: 80,
    temperature: 310,
    medium: "Aqueous Colloidal solvent",
    formulas: ["<x²> = 2 * D * t", "D = k_B * T / (6 * π * η * r)"],
    explain: "Displays random motions of heavy pollen particles struck by fast water molecules.",
    steps: "1. Place pollen targets inside warm water.\n2. Track erratic, zig-zag travel paths.\n3. Plot random trail shapes over time.",
    theory: "Random molecular collisions push heavy particles in erratic directions.",
    hint: "Heat water to speed up erratic particle movements.",
    conceptAnalysis: "Random thermal hits from solvent molecules drive pollen relocations in irregular directions.",
    commonPitfall: "Thinking erratic movements are driven by internal particle life forces.",
    formulaConcept: "v_mean = sqrt(8 * k_B * T / (π * m))"
  },
  {
    id: "entropy_gas_mix",
    name: "Entropy Gas Mixing dispersion",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 50,
    velocity: 65,
    temperature: 298,
    medium: "Mixed gas chamber",
    formulas: ["ΔS = n * R * ln(V_final / V_initial)"],
    explain: "Demonstrates irreversible gas mixing that increases system entropy states.",
    steps: "1. Release partition limits between two distinct gases.\n2. Observe random mixing movements.\n3. Measure system entropy increases.",
    theory: "Thermodynamics shows systems naturally shift toward disordered mixed states, as mixing is highly likely.",
    hint: "Heat chambers to accelerate gas mixing speeds.",
    conceptAnalysis: "Gas particles spread randomly to fill space, shifting systems from ordered states to disordered mixtures.",
    commonPitfall: "Expecting mixed gases to separate on their own without external energy.",
    formulaConcept: "S = k_B * ln(W)"
  },
  {
    id: "archimedes_float",
    name: "Archimedes Buoyancy Float force",
    category: "Thermal/Fluid",
    template: "projectile",
    gravity: 9.8,
    mass: 80,
    velocity: 10,
    temperature: 290,
    medium: "Saline Pool water",
    formulas: ["F_buoyant = ρ_fluid * V_submerged * g", "F_net = F_buoyant - m*g"],
    explain: "Measures upward buoyant force balancing gravity loads of submerged blocks.",
    steps: "1. Push blocks into liquid water.\n2. Measure displaced fluid weights.\n3. Observe blocks floating at balance levels.",
    theory: "Submerged objects experience upward buoyant forces that match displaced water weights.",
    hint: "Increase fluid salinity to float submerged blocks higher.",
    conceptAnalysis: "Liquid pressure increases with depth, producing upward forces that counter gravitational loads.",
    commonPitfall: "Thinking buoyant forces scale with the atmospheric pressure above liquids.",
    formulaConcept: "Buoyancy = Volume * ρ * 9.8"
  },
  {
    id: "poiseuille_viscosity",
    name: "Poiseuille Viscous Tube flow",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 65,
    velocity: 30,
    temperature: 295,
    medium: "Glycerin lubricant",
    formulas: ["Q = (π * ΔP * r⁴) / (8 * η * L)"],
    explain: "Measures speed drops in thick fluids passing through narrow tubes under viscosity constraints.",
    steps: "1. Pump thick glycerins through narrow tubes.\n2. Trace fast flow speeds along center lines.\n3. Note speed dropping to zero near tube walls.",
    theory: "Viscous friction slows fluid boundaries next to tube walls, creating parabolic speed profiles.",
    hint: "Warm fluids to lower viscosity and boost flow volumes.",
    conceptAnalysis: "Liquid border friction forces boundary velocities to zero, forming laminar speed shapes.",
    commonPitfall: "Believing doubling tube radius merely doubles flow volumes (radius increases flow by exactly 16x).",
    formulaConcept: "R_flow = (8 * η * L) / (π * r⁴)"
  },
  {
    id: "torricelli_vacuum_jet",
    name: "Torricelli Liquid Drain jet",
    category: "Thermal/Fluid",
    template: "projectile",
    gravity: 9.8,
    mass: 105,
    velocity: 45,
    temperature: 290,
    medium: "Aqueduct channel",
    formulas: ["v_exit = sqrt(2 * g * h_depth)"],
    explain: "Calculates liquid drain speeds from tank orifices under gravitational pressure.",
    steps: "1. Open drain holes at tank bases.\n2. Launch parabolic exit streams.\n3. Watch exit speeds decline as liquid levels drop.",
    theory: "Exit speeds convert potential liquid height energies into active forward exit velocities.",
    hint: "Increase gravity settings to watch drain speeds climb.",
    conceptAnalysis: "Gravity pressure drives drain velocities, matching exit speeds with free-fall velocities from equal heights.",
    commonPitfall: "Expecting exit speeds to remain constant as tanks drain.",
    formulaConcept: "v = sqrt(19.6 * depth)"
  },
  {
    id: "carnot_cycle",
    name: "Carnot Thermal Engine efficiency",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 100,
    velocity: 20,
    temperature: 600, // Thot
    medium: "Helium gas cylinder",
    formulas: ["η_max = 1 - (T_cold / T_hot)"],
    explain: "Models ideal thermodynamic efficiency limits of heat engines running Carnot cycles.",
    steps: "1. Run gas cylinders through hot isotherm expansions.\n2. Complete adiabatic cooling and cold isotherm contractions.\n3. Measure mechanical work output loops.",
    theory: "Carnot engines set maximum efficiency limits for thermal-to-mechanical energy conversions.",
    hint: "Increase source temperatures to broaden efficiency bands.",
    conceptAnalysis: "Ideal cycles lose some heat to cold drains to meet thermodynamic laws, defining maximum conversion efficiencies.",
    commonPitfall: "Thinking lubrication can push engine efficiencies to 100%.",
    formulaConcept: "Work_net = Q_added - Q_lost"
  },
  {
    id: "mach_sonic_shock",
    name: "Mach Sonic Shock Wave cone",
    category: "Waves & Sound",
    template: "wave",
    gravity: 9.8,
    mass: 40,
    velocity: 150, // extreme high velocity
    temperature: 260,
    medium: "Cryogenic gas tube",
    formulas: ["sin(α) = 1 / Mach"],
    explain: "Models high-speed shock cones as emitters exceed local wave travel limits.",
    steps: "1. Fire projectiles through gas chambers at Mach 1.5.\n2. Intersect waves to form shock envelopes.\n3. Measure shock angles.",
    theory: "Objects moving faster than waves pile wave fronts into physical conical shock regions.",
    hint: "Increase speed to narrow trailing shock envelope angles.",
    conceptAnalysis: "Overlapping wave fronts compress energy into physical shock lines, creating boom signals.",
    commonPitfall: "Expecting shock boundaries to form when speeds are subsonic.",
    formulaConcept: "Mach = Velocity / Wave_Speed"
  },
  {
    id: "van_der_waals_gas",
    name: "Van der Waals Gas Cluster",
    category: "Thermal/Fluid",
    template: "wave",
    gravity: 9.8,
    mass: 55,
    velocity: 50,
    temperature: 150, // low temp
    medium: "Xenon atoms matrix",
    formulas: ["(P + a*n²/V²) * (V - n*b) = n * R * T"],
    explain: "Simulates real-world gas behaviors where molecular volumes and attractions modify classical gas laws.",
    steps: "1. Compress gas systems close to liquid states.\n2. Observe molecular attractions pulling gas atoms closer.\n3. Note pressure drops below ideal calculations.",
    theory: "Real gas laws include corrections for molecular volumes and attractions between atoms.",
    hint: "Heat systems to disperse attractions, returning gas to ideal behaviors.",
    conceptAnalysis: "Cool gases experience attractive forces that damp wall collisions and lower overall pressures.",
    commonPitfall: "Using ideal gas laws under high-pressure cryogenic conditions.",
    formulaConcept: "P_real = (nRT / (V - nb)) - (a * n² / V²)"
  }
];
